spring:
  application:
    name: smartbarber
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG